# Generated by Django 3.0.5 on 2020-05-13 15:15

import django.core.validators
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0005_auto_20200512_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
