# Generated by Django 3.0.5 on 2020-05-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0007_auto_20200513_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CaptainConsole.Payment'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dateShipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shippingCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='trackingNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
