# Generated by Django 3.0.5 on 2020-05-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0008_auto_20200514_1250'),
        ('CaptainConsole', '0005_userinfo_profile_picture'),
    ]

    operations = [
    ]
