# Generated by Django 3.0.5 on 2020-05-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0010_auto_20200514_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CaptainConsole.Order'),
        ),
    ]
