# Generated by Django 3.0.5 on 2020-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0013_auto_20200514_2051'),
        ('CaptainConsole', '0005_product_discount'),
    ]

    operations = [
    ]
