# Generated by Django 3.0.5 on 2020-05-15 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0014_merge_20200515_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('cardNumber', 'cardExp', 'cardCVC')},
        ),
    ]
