# Generated by Django 3.0.5 on 2020-05-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CaptainConsole', '0015_auto_20200515_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='paymentInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CaptainConsole.Payment'),
        ),
    ]
